### ISSUE TITLE
Version 2.02 更新後 Ecourse 功能不正常

### ISSUE THREAD

**Issue by wl00887404** [cculife/CCULife#18]
可以從 TimeTable 取得 Course
但 Ecourse 沒辦法取得公告
我有嘗試看過 CourseActivity
但功力不夠找不太到 Fetch 在哪觸發

如果學長能給些題點
我很樂意繼續試試解決這個 Issue

**Comment by DanSnow** [comment]
應該是這邊吧
https://github.com/Zankio/CCULife/blob/master/ccudata/src/main/java/org/zankio/ccudata/ecourse/source/remote/AnnounceSource.java

**Comment by Zankio** [comment]
這個東西有點複雜 XD
流程如下
隨意發問

---

### Fetch 
CourseAnnounceFragment 呼叫 course 裡面 `getAnnounces`
https://github.com/Zankio/CCULife/blob/b0fe3dd510c5f196c4d4ebd4afd3713174fa6641/CCULife/src/main/java/org/zankio/cculife/ui/ecourse/CourseAnnounceFragment.java#L86

getAnnounces 呼叫 `ecourse.fetch (AnnounceSource.request(this))`
https://github.com/Zankio/CCULife/blob/b0fe3dd510c5f196c4d4ebd4afd3713174fa6641/ccudata/src/main/java/org/zankio/ccudata/ecourse/model/Course.java#L49-L51

ecourse extend ccudata.base.Repository 所以實際呼叫 Repository 的 fetch
https://github.com/Zankio/CCULife/blob/b0fe3dd510c5f196c4d4ebd4afd3713174fa6641/ccudata/src/main/java/org/zankio/ccudata/base/Repository.java#L64

fetch 裡面會取得對應的 Source 也就是 AnnounceSource
https://github.com/Zankio/CCULife/blob/b0fe3dd510c5f196c4d4ebd4afd3713174fa6641/ccudata/src/main/java/org/zankio/ccudata/base/Repository.java#L68

呼叫 executeSource 
https://github.com/Zankio/CCULife/blob/b0fe3dd510c5f196c4d4ebd4afd3713174fa6641/ccudata/src/main/java/org/zankio/ccudata/base/Repository.java#L70

executeSource 會呼叫對應 source 的 fetch
https://github.com/Zankio/CCULife/blob/b0fe3dd510c5f196c4d4ebd4afd3713174fa6641/ccudata/src/main/java/org/zankio/ccudata/base/Repository.java#L155

AnnounceSource 繼承 HTTPJsoupSource -> HTTPSource -> FetchParseSource
所以 fetch 會執行 FetchParseSource  fetch 的
https://github.com/Zankio/CCULife/blob/b0fe3dd510c5f196c4d4ebd4afd3713174fa6641/ccudata/src/main/java/org/zankio/ccudata/base/source/FetchParseSource.java#L10-L12

所以 FetchParseSource  fetch 的會執行 HTTPSource  內部的 override 的 fetch
FetchParseSource abstract method
https://github.com/Zankio/CCULife/blob/b0fe3dd510c5f196c4d4ebd4afd3713174fa6641/ccudata/src/main/java/org/zankio/ccudata/base/source/FetchParseSource.java#L14

HTTPSource  內部的 override 的 fetch 回傳HTTPResponse
https://github.com/Zankio/CCULife/blob/b0fe3dd510c5f196c4d4ebd4afd3713174fa6641/ccudata/src/main/java/org/zankio/ccudata/base/source/http/HTTPSource.java#L26-L42


---
### Parse

呼叫完回到 FetchParseSource 呼叫 parse
https://github.com/Zankio/CCULife/blob/b0fe3dd510c5f196c4d4ebd4afd3713174fa6641/ccudata/src/main/java/org/zankio/ccudata/base/source/FetchParseSource.java#L10-L12

parse  寫在 HTTPJsoupSource 裡面會呼叫另外一的parse
https://github.com/Zankio/CCULife/blob/b0fe3dd510c5f196c4d4ebd4afd3713174fa6641/ccudata/src/main/java/org/zankio/ccudata/base/source/http/HTTPJsoupSource.java#L11-L13

parse(Request<TData, TArgument> request, HttpResponse response, Document document)
https://github.com/Zankio/CCULife/blob/b0fe3dd510c5f196c4d4ebd4afd3713174fa6641/ccudata/src/main/java/org/zankio/ccudata/base/source/http/HTTPJsoupSource.java#L15

由 AnnounceSource 做override parse 這個method
https://github.com/Zankio/CCULife/blob/b0fe3dd510c5f196c4d4ebd4afd3713174fa6641/ccudata/src/main/java/org/zankio/ccudata/ecourse/source/remote/AnnounceSource.java#L39

**Comment by Zankio** [comment]
結果好像是ecourse 的ssl又出問題了 :cry: 
又沒有放 full chain 上去...
上次 ecourse 用好我把相關的東西拔掉後這次又來...

**Comment by wl00887404** [comment]
![image](https://user-images.githubusercontent.com/11714950/30679933-5809da44-9ecf-11e7-8d36-69e7fd1ee572.png)

我的爬蟲也爆炸了:cry:

學長有聽說半年後 ecourse 要換 moodle (一個課程的CMS框架) 的消息嗎？
聽說 IOS 不打算繼續維護了
不然重弄新的 parser

**Comment by henrybear327** [comment]
iOS 這邊暫時觀望
新功能會加但是主要先以維護為主

畢竟moodle的好處是有api 
不用自己搞parser

**Comment by henrybear327** [comment]
前些陣子有跟計中聯絡過moodle 的事情
啊本來單一入口也有moodle 的連結
但是現在消失了

總之等待消息再說啦

**Comment by wl00887404** [comment]
hmm...
現在又正常了
實在不太懂 ecourse 的運作...

**Comment by Zankio** [comment]
moodle 看起來好麻煩... 😞
